feishu:
  # 该区域请于飞书开放平台查询本机器人信息,详见
  # https://open.feishu.cn/document/home/develop-a-bot-in-5-minutes/coding
  APP_ID: cli_a385f***********
  APP_SECRET: RxvCp***************************
  VERIFICATION_TOKEN: CX5YW***************************
  ENCRYPT_KEY: ''
  LARK_HOST: "https://open.feishu.cn"

server:
  # 端口，请根据实际情况为准
  PORT: 3000